apiVersion: v1
kind: Service
metadata:
  name: appium
  namespace: e2e
  labels:
    app: appium-emulator
spec:
  selector:
    app: appium-emulator
  type: ClusterIP
  ports:
    - name: appium
      port: 4723
      targetPort: appium
    - name: vnc
      port: 6080
      targetPort: vnc
